-- =============================================================================
-- 05_transforms.sql - Streams + Tasks for Actuarial Data Enrichment
-- =============================================================================
-- Run after 01_stages_formats.sql (tables must exist) and 03_load_parquet.sql
-- (data should be loaded to see streams in action).
--
-- Creates: Streams for CDC, destination tables, Tasks for automation
-- =============================================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE ACTUARIAL_LAB_DB;
USE WAREHOUSE ACTUARIAL_TRANSFORM_WH;

-- =============================================================================
-- STEP 1: Create Streams on RAW tables
-- =============================================================================
-- APPEND_ONLY = TRUE because actuarial results are immutable once written;
-- we only care about new inserts, not updates or deletes.

USE SCHEMA RAW;

CREATE OR REPLACE STREAM ACTUARIAL_RESULTS_STREAM
    ON TABLE ACTUARIAL_RESULTS_RAW
    APPEND_ONLY = TRUE
    COMMENT = 'Tracks new actuarial result records for enrichment';

CREATE OR REPLACE STREAM RUN_METADATA_STREAM
    ON TABLE RUN_METADATA_RAW
    APPEND_ONLY = TRUE
    COMMENT = 'Tracks new run metadata for join enrichment';

-- Verify streams
SHOW STREAMS IN SCHEMA RAW;
SELECT SYSTEM$STREAM_HAS_DATA('ACTUARIAL_RESULTS_STREAM') AS HAS_DATA;

-- =============================================================================
-- STEP 2: Create destination tables (Silver + Gold layers)
-- =============================================================================

-- STAGE schema: Enriched results (Silver layer)
USE SCHEMA STAGE;

CREATE OR REPLACE TABLE RESULTS_ENRICHED (
    RUN_ID              STRING          NOT NULL,
    SCENARIO_ID         STRING          NOT NULL,
    MODEL_POINT_ID      STRING          NOT NULL,
    COHORT_ID           STRING          NOT NULL,
    VALUATION_DATE      DATE            NOT NULL,
    REPORTING_STANDARD  STRING          NOT NULL,
    -- Actuarial measurements
    PRESENT_VALUE_FUTURE_CASHFLOWS NUMBER(18,2),
    CONTRACTUAL_SERVICE_MARGIN     NUMBER(18,2),
    LOSS_COMPONENT      NUMBER(18,2),
    RISK_ADJUSTMENT     NUMBER(18,2),
    BEST_ESTIMATE_LIABILITY        NUMBER(18,2),
    INSURANCE_REVENUE   NUMBER(18,2),
    INSURANCE_SERVICE_EXPENSE      NUMBER(18,2),
    -- Enrichment from run metadata
    MODEL_VERSION       STRING                      COMMENT 'From RUN_METADATA',
    RUN_STATUS          STRING                      COMMENT 'From RUN_METADATA',
    RUN_DURATION_SEC    NUMBER(12,0)                COMMENT 'From RUN_METADATA',
    -- Derived metrics
    NET_LIABILITY       NUMBER(18,2)                COMMENT 'BEL + RA + CSM',
    CSM_RATIO           NUMBER(8,4)                 COMMENT 'CSM / PVFCF',
    _PROCESSED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- CURATED schema: Cohort-level aggregates (Gold layer)
USE SCHEMA CURATED;

CREATE OR REPLACE TABLE COHORT_SUMMARY (
    COHORT_ID           STRING          NOT NULL,
    VALUATION_DATE      DATE            NOT NULL,
    REPORTING_STANDARD  STRING          NOT NULL,
    MODEL_POINT_COUNT   NUMBER(10,0),
    TOTAL_BEL           NUMBER(18,2)    COMMENT 'Sum of best estimate liability',
    TOTAL_RA            NUMBER(18,2)    COMMENT 'Sum of risk adjustment',
    TOTAL_CSM           NUMBER(18,2)    COMMENT 'Sum of CSM',
    TOTAL_NET_LIABILITY NUMBER(18,2)    COMMENT 'Sum of net liability',
    AVG_CSM_RATIO       NUMBER(8,4)     COMMENT 'Avg CSM / PVFCF',
    TOTAL_REVENUE       NUMBER(18,2),
    TOTAL_EXPENSE       NUMBER(18,2),
    _UPDATED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (COHORT_ID, VALUATION_DATE, REPORTING_STANDARD)
);

CREATE OR REPLACE TABLE RUN_COMPARISON (
    RUN_ID_A            STRING          NOT NULL,
    RUN_ID_B            STRING          NOT NULL,
    COHORT_ID           STRING          NOT NULL,
    REPORTING_STANDARD  STRING          NOT NULL,
    DELTA_BEL           NUMBER(18,2),
    DELTA_CSM           NUMBER(18,2),
    DELTA_NET_LIABILITY NUMBER(18,2),
    _COMPUTED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- =============================================================================
-- STEP 3: Manually run the enrichment to understand the logic
-- =============================================================================

USE SCHEMA STAGE;

-- Insert enriched results by joining raw results with run metadata
INSERT INTO RESULTS_ENRICHED (
    RUN_ID, SCENARIO_ID, MODEL_POINT_ID, COHORT_ID,
    VALUATION_DATE, REPORTING_STANDARD,
    PRESENT_VALUE_FUTURE_CASHFLOWS, CONTRACTUAL_SERVICE_MARGIN,
    LOSS_COMPONENT, RISK_ADJUSTMENT, BEST_ESTIMATE_LIABILITY,
    INSURANCE_REVENUE, INSURANCE_SERVICE_EXPENSE,
    MODEL_VERSION, RUN_STATUS, RUN_DURATION_SEC,
    NET_LIABILITY, CSM_RATIO
)
SELECT
    r.RUN_ID,
    r.SCENARIO_ID,
    r.MODEL_POINT_ID,
    r.COHORT_ID,
    r.VALUATION_DATE,
    r.REPORTING_STANDARD,
    r.PRESENT_VALUE_FUTURE_CASHFLOWS,
    r.CONTRACTUAL_SERVICE_MARGIN,
    r.LOSS_COMPONENT,
    r.RISK_ADJUSTMENT,
    r.BEST_ESTIMATE_LIABILITY,
    r.INSURANCE_REVENUE,
    r.INSURANCE_SERVICE_EXPENSE,
    -- Enrichment from run metadata
    m.MODEL_VERSION,
    m.STATUS AS RUN_STATUS,
    m.TOTAL_COMPUTE_SECONDS AS RUN_DURATION_SEC,
    -- Derived: Net Liability = BEL + RA + CSM (or Loss Component)
    COALESCE(r.BEST_ESTIMATE_LIABILITY, 0)
        + COALESCE(r.RISK_ADJUSTMENT, 0)
        + COALESCE(r.CONTRACTUAL_SERVICE_MARGIN, 0) AS NET_LIABILITY,
    -- Derived: CSM ratio
    CASE
        WHEN r.PRESENT_VALUE_FUTURE_CASHFLOWS != 0
        THEN r.CONTRACTUAL_SERVICE_MARGIN / r.PRESENT_VALUE_FUTURE_CASHFLOWS
        ELSE NULL
    END AS CSM_RATIO
FROM RAW.ACTUARIAL_RESULTS_STREAM r
LEFT JOIN RAW.RUN_METADATA_RAW m ON r.RUN_ID = m.RUN_ID;

-- Verify
SELECT * FROM RESULTS_ENRICHED ORDER BY _PROCESSED_AT DESC LIMIT 10;

-- Stream should be consumed
SELECT SYSTEM$STREAM_HAS_DATA('RAW.ACTUARIAL_RESULTS_STREAM') AS HAS_DATA;

-- =============================================================================
-- STEP 4: Aggregate into COHORT_SUMMARY (Gold layer)
-- =============================================================================

MERGE INTO CURATED.COHORT_SUMMARY tgt
USING (
    SELECT
        COHORT_ID,
        VALUATION_DATE,
        REPORTING_STANDARD,
        COUNT(*) AS MODEL_POINT_COUNT,
        SUM(BEST_ESTIMATE_LIABILITY) AS TOTAL_BEL,
        SUM(RISK_ADJUSTMENT) AS TOTAL_RA,
        SUM(CONTRACTUAL_SERVICE_MARGIN) AS TOTAL_CSM,
        SUM(NET_LIABILITY) AS TOTAL_NET_LIABILITY,
        AVG(CSM_RATIO) AS AVG_CSM_RATIO,
        SUM(INSURANCE_REVENUE) AS TOTAL_REVENUE,
        SUM(INSURANCE_SERVICE_EXPENSE) AS TOTAL_EXPENSE
    FROM STAGE.RESULTS_ENRICHED
    GROUP BY COHORT_ID, VALUATION_DATE, REPORTING_STANDARD
) src
ON  tgt.COHORT_ID = src.COHORT_ID
AND tgt.VALUATION_DATE = src.VALUATION_DATE
AND tgt.REPORTING_STANDARD = src.REPORTING_STANDARD
WHEN MATCHED THEN UPDATE SET
    MODEL_POINT_COUNT = src.MODEL_POINT_COUNT,
    TOTAL_BEL = src.TOTAL_BEL,
    TOTAL_RA = src.TOTAL_RA,
    TOTAL_CSM = src.TOTAL_CSM,
    TOTAL_NET_LIABILITY = src.TOTAL_NET_LIABILITY,
    AVG_CSM_RATIO = src.AVG_CSM_RATIO,
    TOTAL_REVENUE = src.TOTAL_REVENUE,
    TOTAL_EXPENSE = src.TOTAL_EXPENSE,
    _UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    COHORT_ID, VALUATION_DATE, REPORTING_STANDARD, MODEL_POINT_COUNT,
    TOTAL_BEL, TOTAL_RA, TOTAL_CSM, TOTAL_NET_LIABILITY, AVG_CSM_RATIO,
    TOTAL_REVENUE, TOTAL_EXPENSE
) VALUES (
    src.COHORT_ID, src.VALUATION_DATE, src.REPORTING_STANDARD, src.MODEL_POINT_COUNT,
    src.TOTAL_BEL, src.TOTAL_RA, src.TOTAL_CSM, src.TOTAL_NET_LIABILITY, src.AVG_CSM_RATIO,
    src.TOTAL_REVENUE, src.TOTAL_EXPENSE
);

SELECT * FROM CURATED.COHORT_SUMMARY;

-- =============================================================================
-- STEP 5: Create Tasks to automate the pipeline
-- =============================================================================
-- Task chain: TASK_ENRICH_RESULTS → TASK_AGGREGATE_COHORTS

USE SCHEMA STAGE;

CREATE OR REPLACE TASK TASK_ENRICH_RESULTS
    WAREHOUSE = ACTUARIAL_TRANSFORM_WH
    SCHEDULE = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('ACTUARIAL_LAB_DB.RAW.ACTUARIAL_RESULTS_STREAM')
AS
INSERT INTO ACTUARIAL_LAB_DB.STAGE.RESULTS_ENRICHED (
    RUN_ID, SCENARIO_ID, MODEL_POINT_ID, COHORT_ID,
    VALUATION_DATE, REPORTING_STANDARD,
    PRESENT_VALUE_FUTURE_CASHFLOWS, CONTRACTUAL_SERVICE_MARGIN,
    LOSS_COMPONENT, RISK_ADJUSTMENT, BEST_ESTIMATE_LIABILITY,
    INSURANCE_REVENUE, INSURANCE_SERVICE_EXPENSE,
    MODEL_VERSION, RUN_STATUS, RUN_DURATION_SEC,
    NET_LIABILITY, CSM_RATIO
)
SELECT
    r.RUN_ID, r.SCENARIO_ID, r.MODEL_POINT_ID, r.COHORT_ID,
    r.VALUATION_DATE, r.REPORTING_STANDARD,
    r.PRESENT_VALUE_FUTURE_CASHFLOWS, r.CONTRACTUAL_SERVICE_MARGIN,
    r.LOSS_COMPONENT, r.RISK_ADJUSTMENT, r.BEST_ESTIMATE_LIABILITY,
    r.INSURANCE_REVENUE, r.INSURANCE_SERVICE_EXPENSE,
    m.MODEL_VERSION,
    m.STATUS,
    m.TOTAL_COMPUTE_SECONDS,
    COALESCE(r.BEST_ESTIMATE_LIABILITY, 0) + COALESCE(r.RISK_ADJUSTMENT, 0) + COALESCE(r.CONTRACTUAL_SERVICE_MARGIN, 0),
    CASE WHEN r.PRESENT_VALUE_FUTURE_CASHFLOWS != 0
         THEN r.CONTRACTUAL_SERVICE_MARGIN / r.PRESENT_VALUE_FUTURE_CASHFLOWS
         ELSE NULL END
FROM ACTUARIAL_LAB_DB.RAW.ACTUARIAL_RESULTS_STREAM r
LEFT JOIN ACTUARIAL_LAB_DB.RAW.RUN_METADATA_RAW m ON r.RUN_ID = m.RUN_ID;

-- Chained task: runs after enrichment completes
USE SCHEMA CURATED;

CREATE OR REPLACE TASK TASK_AGGREGATE_COHORTS
    WAREHOUSE = ACTUARIAL_TRANSFORM_WH
    AFTER ACTUARIAL_LAB_DB.STAGE.TASK_ENRICH_RESULTS
AS
MERGE INTO ACTUARIAL_LAB_DB.CURATED.COHORT_SUMMARY tgt
USING (
    SELECT
        COHORT_ID, VALUATION_DATE, REPORTING_STANDARD,
        COUNT(*) AS MODEL_POINT_COUNT,
        SUM(BEST_ESTIMATE_LIABILITY) AS TOTAL_BEL,
        SUM(RISK_ADJUSTMENT) AS TOTAL_RA,
        SUM(CONTRACTUAL_SERVICE_MARGIN) AS TOTAL_CSM,
        SUM(NET_LIABILITY) AS TOTAL_NET_LIABILITY,
        AVG(CSM_RATIO) AS AVG_CSM_RATIO,
        SUM(INSURANCE_REVENUE) AS TOTAL_REVENUE,
        SUM(INSURANCE_SERVICE_EXPENSE) AS TOTAL_EXPENSE
    FROM ACTUARIAL_LAB_DB.STAGE.RESULTS_ENRICHED
    GROUP BY COHORT_ID, VALUATION_DATE, REPORTING_STANDARD
) src
ON  tgt.COHORT_ID = src.COHORT_ID
AND tgt.VALUATION_DATE = src.VALUATION_DATE
AND tgt.REPORTING_STANDARD = src.REPORTING_STANDARD
WHEN MATCHED THEN UPDATE SET
    MODEL_POINT_COUNT = src.MODEL_POINT_COUNT,
    TOTAL_BEL = src.TOTAL_BEL, TOTAL_RA = src.TOTAL_RA,
    TOTAL_CSM = src.TOTAL_CSM, TOTAL_NET_LIABILITY = src.TOTAL_NET_LIABILITY,
    AVG_CSM_RATIO = src.AVG_CSM_RATIO,
    TOTAL_REVENUE = src.TOTAL_REVENUE, TOTAL_EXPENSE = src.TOTAL_EXPENSE,
    _UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    COHORT_ID, VALUATION_DATE, REPORTING_STANDARD, MODEL_POINT_COUNT,
    TOTAL_BEL, TOTAL_RA, TOTAL_CSM, TOTAL_NET_LIABILITY, AVG_CSM_RATIO,
    TOTAL_REVENUE, TOTAL_EXPENSE
) VALUES (
    src.COHORT_ID, src.VALUATION_DATE, src.REPORTING_STANDARD, src.MODEL_POINT_COUNT,
    src.TOTAL_BEL, src.TOTAL_RA, src.TOTAL_CSM, src.TOTAL_NET_LIABILITY, src.AVG_CSM_RATIO,
    src.TOTAL_REVENUE, src.TOTAL_EXPENSE
);

-- =============================================================================
-- STEP 6: Resume tasks (they are created in SUSPENDED state)
-- =============================================================================
-- Resume child first, then parent
ALTER TASK ACTUARIAL_LAB_DB.CURATED.TASK_AGGREGATE_COHORTS RESUME;
ALTER TASK ACTUARIAL_LAB_DB.STAGE.TASK_ENRICH_RESULTS RESUME;

-- Verify task state
SHOW TASKS IN DATABASE ACTUARIAL_LAB_DB;
